# Lib

In [1]:
import json

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import networkx as nx

from sklearn.decomposition import PCA

import warnings
warnings.filterwarnings("ignore")

# Data

In [2]:
# Load Labels
df_target = pd.read_csv("../../data/github_social_network/musae_git_target.csv")
df_target.columns = df_target.columns.str.strip().str.lower().str.replace(" ", "_")

# Load Edges
df_edges = pd.read_csv("../../data/github_social_network/musae_git_edges.csv")
df_edges.columns = df_edges.columns.str.strip().str.lower().str.replace(" ", "_")

# Load Features
with open("../../data/github_social_network/musae_git_features.json", "r") as f:
    features_json = json.load(f)

# Combination

## Merge

In [3]:
df_target.rename(columns={"id": "source"}, inplace=True)
df_target.head()

   source          name  ml_target
0       0        Eiryyy          0
1       1    shawflying          0
2       2   JpMCarrilho          1
3       3     SuhwanCha          0
4       4  sunilangadi2          1

In [4]:
df_edges.rename(columns={"id_1": "source", "id_2": "target"}, inplace=True)
df_edges.head()

   source  target
0       0   23977
1       1   34526
2       1    2370
3       1   14683
4       1   29982

In [5]:
df = df_edges.merge(df_target, on="source", how="left")

In [6]:
df.head()

   source  target        name  ml_target
0       0   23977      Eiryyy          0
1       1   34526  shawflying          0
2       1    2370  shawflying          0
3       1   14683  shawflying          0
4       1   29982  shawflying          0

# Export

In [8]:
df.to_csv("../../data/processed/processed.csv", index=False)